env:
  browser: true
  commonjs: true
  es2021: true
  jest/globals: true
extends:
  - airbnb-base
  - prettier
parserOptions:
  ecmaVersion: latest
rules:
  no-underscore-dangle: 0
  class-methods-use-this: 0
plugins:
  - jest
