name: Test Charmhub Upload

on:
- push
- pull_request

jobs:
  ensure-compiled:
    runs-on: ubuntu-latest
    name: Ensure ncc compilation
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: ./hooks/pre-commit

  test-charmhub-upload:
    runs-on: ubuntu-latest
    name: Test charmhub upload
    steps:
      - uses: actions/checkout@v2

      - uses: ./
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          charm-path: test-charm/
          upload-image: "false"

      # - uses: ./
      #   with:
      #     credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
      #     bundle-path: test-bundle/

      - uses: actions/upload-artifact@v2
        with:
          name: my-logs
          path: /home/runner/snap/charmcraft/common/cache/charmcraft/log/
